spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ojttest?serverTimezone=Asia/Seoul #ojttest => DB_NAME
    username: hosun1 # DB USER
    password: 1234 # PASSWORD

mybatis:
  mapper-locations: mapper/*.xml